import esbuild from "esbuild";
import { builtinModules } from "node:module";
import fs from "fs/promises";

async function copyAssets() {
	await fs.mkdir("build", { recursive: true });
	await fs.copyFile("manifest.json", "build/manifest.json");

	await fs.writeFile(
		"build/styles.css",
		(
			await esbuild.transform(
				await fs.readFile("src/styles.css", "utf8"),
				{ loader: "css", minify: true },
			)
		).code,
	);
}

const copyAssetsPlugin = {
	name: "copy-assets",
	setup(build) {
		build.onEnd(() => copyAssets());
	},
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

await esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	treeShaking: true,
	outfile: "build/main.js",
	minify: true,
	plugins: [copyAssetsPlugin],
});
