import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs/promises";

const prod = process.argv[2] === "production";

async function copyAssets() {
	await fs.mkdir("build", { recursive: true });
	await fs.copyFile("manifest.json", "build/manifest.json");

	if (prod) {
		const css = await fs.readFile("src/styles.css", "utf8");
		const result = await esbuild.transform(css, {
			loader: "css",
			minify: true,
		});
		await fs.writeFile("build/styles.css", result.code);
	} else {
		await fs.copyFile("src/styles.css", "build/styles.css");
	}
}

const copyAssetsPlugin = {
	name: "copy-assets",
	setup(build) {
		build.onEnd(() => copyAssets());
	},
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "build/main.js",
	minify: prod,
	plugins: [copyAssetsPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
